### ISSUE TITLE
ffmpeg not installed error

### ISSUE THREAD

**Issue by mrodus** [nandyalu/trailarr#9]
I can't get the trailers to download. The logs tell me that ffmpeg is not installed, but I still see the same message when I install it inside the container.

```log
ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
2024-08-06T22:06:16+0530 [ERROR|video|L186]: TrailersDownloader: Failed to download video from https://www.youtube.com/watch?v=FQ63rqSRrEI
Traceback (most recent call last):
  File "/app/backend/core/download/video.py", line 184, in download_video
    ydl.download([url])
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3607, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3582, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3015, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3441, in process_info
    self.report_error(f'{msg}. Aborting due to --abort-on-error')
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1092, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
ERROR: TrailersDownloader: Failed to download video from https://www.youtube.com/watch?v=FQ63rqSRrEI
Traceback (most recent call last):
  File "/app/backend/core/download/video.py", line 184, in download_video
    ydl.download([url])
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3607, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3582, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3015, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3441, in process_info
    self.report_error(f'{msg}. Aborting due to --abort-on-error')
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1092, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
2024-08-06T22:06:16+0530 [ERROR|base|L131]: Job "Download Trailer for Kung Fu Panda 2 (trigger: date[2024-08-06 22:05:59 IST], next run at: 2024-08-06 22:05:59 IST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/tasks/download_trailers.py", line 91, in _download_trailer_by_id
    download_media = download_trailers([mediaT], is_movie)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: Job "Download Trailer for Kung Fu Panda 2 (trigger: date[2024-08-06 22:05:59 IST], next run at: 2024-08-06 22:05:59 IST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/tasks/download_trailers.py", line 91, in _download_trailer_by_id
    download_media = download_trailers([mediaT], is_movie)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 230, in download_trailers
    if download_trailer(media, trailer_folder, is_movie):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 115, in download_trailer
    output_file = download_video(trailer_url, f"/tmp/{media.id}-trailer.%(ext)s")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/video.py", line 187, in download_video
    return str(data["filepath"])
               ~~~~^^^^^^^^^^^^
KeyError: 'filepath'
  File "/app/backend/core/download/trailer.py", line 230, in download_trailers
    if download_trailer(media, trailer_folder, is_movie):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 115, in download_trailer
    output_file = download_video(trailer_url, f"/tmp/{media.id}-trailer.%(ext)s")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/video.py", line 187, in download_video
    return str(data["filepath"])
               ~~~~^^^^^^^^^^^^
KeyError: 'filepath'
```

My compose file:
```yaml
  trailarr:
      image: nandyalu/trailarr:latest
      container_name: trailarr
      environment:
          - TZ=${TZ}
      ports:
          - 7889:7889
      volumes:
          - ${HOME}/trailarr/data:/data
          - ${HOME}/media:/media
      restart: unless-stopped
```

**Comment by nandyalu** [comment]
ffmpeg comes pre-installed with the container image. What OS are you using?

**Comment by mrodus** [comment]
> ffmpeg comes pre-installed with the container image. What OS are you using?

Debian

**Comment by nandyalu** [comment]
I think a Raspberry Pi supported version of ffmpeg is needed, I will check on this

**Comment by mrodus** [comment]
> Can you run `dpkg --print-architecture` and post the output?

arm64
